'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertCircle, ArrowLeft, ArrowRight, Check, Loader2, LockKeyhole } from 'lucide-react'
import { calculateAge, fellowshipApplicationSchema, fellowshipInterests, fellowshipSkills, type FellowshipApplicationValues } from '@/lib/fellowship'

const steps = ['Personal information', 'Education & background', 'Climate experience', 'Motivation & leadership', 'Skills & availability', 'Declaration']
const inputClass = 'mt-2 min-h-12 w-full rounded-xl border border-border bg-white px-4 text-foreground outline-none transition placeholder:text-muted-foreground focus:border-primary focus:ring-4 focus:ring-primary/10'
const labelClass = 'text-sm font-bold text-foreground'

const initialValues: FellowshipApplicationValues = {
  fullName: '', email: '', phone: '', gender: '', dateOfBirth: '', age: 0, state: '', lga: '', community: '', country: 'Nigeria', address: '', education: '', fieldOfStudy: '', institution: '', occupation: '', organization: '', role: '', hasClimateExperience: 'No', climateExperience: '', climateInterests: [], motivation: '', communityChallenge: '', proposedImpact: '', leadershipExperience: '', climateLeadership: '', skills: [], digitalLiteracy: '', availability: 'Yes', referralSource: '', declarationAccepted: false, communicationsOptIn: false,
}

function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label className={labelClass}>{label}{required && <span className="ml-1 text-[#b17b00]">*</span>}{children}</label> }
function SelectField({ label, required, value, onChange, options, placeholder = 'Select an option' }: { label: string; required?: boolean; value: string; onChange: (value: string) => void; options: string[]; placeholder?: string }) { return <Field label={label} required={required}><select className={inputClass} value={value} onChange={(event) => onChange(event.target.value)}><option value="">{placeholder}</option>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></Field> }
function TextArea({ label, value, onChange, limit }: { label: string; value: string; onChange: (value: string) => void; limit: number }) { const count = value.trim() ? value.trim().split(/\s+/).length : 0; return <Field label={label} required><textarea className={`${inputClass} min-h-36 resize-y py-3`} value={value} onChange={(event) => onChange(event.target.value)} /><span className={`mt-1 block text-right text-xs ${count > limit ? 'text-red-600' : 'text-[#738479]'}`}>{count}/{limit} words</span></Field> }

export function FellowshipApplicationForm() {
  const router = useRouter()
  const [values, setValues] = useState(initialValues)
  const [currentStep, setCurrentStep] = useState(0)
  const [error, setError] = useState('')
  const [showConfirmation, setShowConfirmation] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const update = <K extends keyof FellowshipApplicationValues>(key: K, value: FellowshipApplicationValues[K]) => setValues((current) => ({ ...current, [key]: value }))
  const toggle = (key: 'climateInterests' | 'skills', value: string) => update(key, values[key].includes(value) ? values[key].filter((item) => item !== value) : [...values[key], value])

  const validateStep = () => {
    const fields: Record<number, (keyof FellowshipApplicationValues)[]> = {
      0: ['fullName', 'email', 'phone', 'gender', 'dateOfBirth', 'state', 'lga', 'country'],
      1: ['education', 'occupation'], 2: ['climateInterests'], 3: ['motivation', 'communityChallenge', 'proposedImpact', 'leadershipExperience', 'climateLeadership'], 4: ['skills', 'digitalLiteracy', 'availability', 'referralSource'], 5: ['declarationAccepted'],
    }
    const activeFields = fields[currentStep]
    const activeSchema = currentStep === 5
      ? fellowshipApplicationSchema
      : fellowshipApplicationSchema.pick(Object.fromEntries(activeFields.map((field) => [field, true])) as never)
    const result = activeSchema.safeParse(values)
    if (!result.success) {
      setError(result.error.issues[0]?.message ?? 'Please review your application before continuing.')
      return false
    }
    if (currentStep === 0 && calculateAge(values.dateOfBirth) < 16) { setError('Applicants must be at least 16 years old.'); return false }
    if (currentStep === 2 && values.hasClimateExperience === 'Yes' && !values.climateExperience?.trim()) { setError('Please describe your climate or environmental experience.'); return false }
    setError(''); return true
  }
  const next = () => { if (validateStep()) setCurrentStep((step) => Math.min(5, step + 1)) }
  const submit = async () => {
    if (!validateStep()) return
    setIsSubmitting(true); setError('')
    try {
      const response = await fetch('/api/fellowship/apply', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...values, age: calculateAge(values.dateOfBirth) }) })
      const result = await response.json()
      if (!response.ok) {
        const existingApplicationId = result.applicationId ? ` Your application ID is ${result.applicationId}.` : ''
        throw new Error(`${result.error || 'Unable to submit application.'}${existingApplicationId}`)
      }
      const applicationId = result.application?.applicationId
      if (!applicationId) throw new Error('Your application was saved, but we could not retrieve its application ID. Please contact the fellowship team.')
      router.push(`/fellowship/success?applicationId=${encodeURIComponent(applicationId)}`)
    } catch (submissionError) { setError((submissionError as Error).message) } finally { setIsSubmitting(false) }
  }

  return <div className="mx-auto max-w-4xl">
    <div className="mb-8 rounded-2xl border border-[#d3e2cf] bg-white p-4 sm:p-6"><div className="flex items-center justify-between"><p className="text-sm font-extrabold text-[#164d2b]">Step {currentStep + 1} of 6</p><p className="text-xs text-[#738479]">{Math.round(((currentStep + 1) / 6) * 100)}% complete</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#e7efe4]"><div className="h-full rounded-full bg-[#2f7b45] transition-all" style={{ width: `${((currentStep + 1) / 6) * 100}%` }} /></div><div className="mt-5 hidden grid-cols-6 gap-2 md:grid">{steps.map((step, index) => <button type="button" key={step} disabled={index > currentStep} onClick={() => index < currentStep && setCurrentStep(index)} className={`text-left text-xs font-bold ${index <= currentStep ? 'text-[#164d2b]' : 'text-[#9aab9d]'}`}><span className={`mr-1 inline-grid h-5 w-5 place-items-center rounded-full ${index < currentStep ? 'bg-[#2f7b45] text-white' : index === currentStep ? 'bg-[#f5cc55] text-[#17351f]' : 'bg-[#e7efe4]'}`}>{index < currentStep ? <Check size={12} /> : index + 1}</span>{step}</button>)}</div></div>

    {error && <div role="alert" className="mb-5 flex items-start gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700"><AlertCircle size={18} className="mt-0.5 shrink-0" />{error}</div>}
    <section className="rounded-3xl border border-[#d3e2cf] bg-white p-5 shadow-[0_18px_50px_rgba(22,77,43,.06)] sm:p-9"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c18f1d]">{String(currentStep + 1).padStart(2, '0')}</p><h1 className="mt-2 text-3xl font-black text-[#164d2b]">{steps[currentStep]}</h1><p className="mt-2 text-sm text-[#738479]">Fields marked with <span className="text-[#b17b00]">*</span> are required.</p></div>
      {currentStep === 0 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Full name" required><input className={inputClass} value={values.fullName} onChange={(e) => update('fullName', e.target.value)} placeholder="Your full name" /></Field><Field label="Email address" required><input type="email" className={inputClass} value={values.email} onChange={(e) => update('email', e.target.value)} placeholder="you@example.com" /></Field><Field label="Phone number" required><input type="tel" className={inputClass} value={values.phone} onChange={(e) => update('phone', e.target.value)} placeholder="080 1234 5678" /></Field><SelectField label="Gender" required value={values.gender} onChange={(v) => update('gender', v)} options={['Male', 'Female', 'Prefer not to say']} /><Field label="Date of birth" required><input type="date" className={inputClass} value={values.dateOfBirth} onChange={(e) => { update('dateOfBirth', e.target.value); update('age', calculateAge(e.target.value)) }} /></Field><Field label="Age"><input readOnly className={`${inputClass} bg-[#f7faf4]`} value={values.dateOfBirth ? calculateAge(values.dateOfBirth) : ''} placeholder="Calculated automatically" /></Field><Field label="State of residence" required><input className={inputClass} value={values.state} onChange={(e) => update('state', e.target.value)} placeholder="e.g. Kaduna" /></Field><Field label="Local Government Area" required><input className={inputClass} value={values.lga} onChange={(e) => update('lga', e.target.value)} placeholder="Your LGA" /></Field><Field label="Community / town"><input className={inputClass} value={values.community} onChange={(e) => update('community', e.target.value)} /></Field><SelectField label="Country" required value={values.country} onChange={(v) => update('country', v)} options={['Nigeria', 'Other']} /><div className="sm:col-span-2"><Field label="Residential address"><textarea className={`${inputClass} min-h-24 py-3`} value={values.address} onChange={(e) => update('address', e.target.value)} /></Field></div></div>}

      {currentStep === 1 && <div className="grid gap-5 sm:grid-cols-2"><SelectField label="Highest educational qualification" required value={values.education} onChange={(v) => update('education', v)} options={['Secondary School', 'Diploma', 'NCE', 'OND', 'HND', "Bachelor's Degree", "Master's Degree", 'PhD', 'Other']} /><SelectField label="Current occupation / status" required value={values.occupation} onChange={(v) => update('occupation', v)} options={['Student', 'Employed', 'Entrepreneur', 'Volunteer', 'Unemployed', 'Other']} /><Field label="Field of study"><input className={inputClass} value={values.fieldOfStudy} onChange={(e) => update('fieldOfStudy', e.target.value)} /></Field><Field label="Institution"><input className={inputClass} value={values.institution} onChange={(e) => update('institution', e.target.value)} /></Field><Field label="Organization / institution"><input className={inputClass} value={values.organization} onChange={(e) => update('organization', e.target.value)} /></Field><Field label="Current role"><input className={inputClass} value={values.role} onChange={(e) => update('role', e.target.value)} /></Field></div>}

      {currentStep === 2 && <div><SelectField label="Have you participated in climate, environmental or sustainability activities?" required value={values.hasClimateExperience} onChange={(v) => update('hasClimateExperience', v as 'Yes' | 'No')} options={['Yes', 'No']} />{values.hasClimateExperience === 'Yes' && <div className="mt-5"><Field label="Please describe your experience" required><textarea className={`${inputClass} min-h-36 py-3`} value={values.climateExperience} onChange={(e) => update('climateExperience', e.target.value)} /><span className="mt-1 block text-right text-xs text-[#738479]">Maximum 500 words</span></Field></div>}<fieldset className="mt-8"><legend className={labelClass}>Which areas are you most interested in?<span className="ml-1 text-[#b17b00]">*</span></legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{fellowshipInterests.map((interest) => <label key={interest} className="flex cursor-pointer items-center gap-3 rounded-xl border border-[#d3e2cf] p-3 text-sm font-semibold text-[#31543b] hover:bg-[#f7faf4]"><input type="checkbox" checked={values.climateInterests.includes(interest)} onChange={() => toggle('climateInterests', interest)} className="h-5 w-5 accent-[#2f7b45]" />{interest}</label>)}</div></fieldset></div>}

      {currentStep === 3 && <div className="space-y-6"><TextArea label="Why do you want to join the Shara Climate Champions Fellowship?" value={values.motivation} onChange={(v) => update('motivation', v)} limit={300} /><TextArea label="What climate or environmental challenge in your community concerns you most?" value={values.communityChallenge} onChange={(v) => update('communityChallenge', v)} limit={300} /><TextArea label="If selected, what positive change would you contribute to your community?" value={values.proposedImpact} onChange={(v) => update('proposedImpact', v)} limit={300} /><TextArea label="Describe a time when you demonstrated leadership, teamwork or community service." value={values.leadershipExperience} onChange={(v) => update('leadershipExperience', v)} limit={300} /><TextArea label="What does climate leadership mean to you?" value={values.climateLeadership} onChange={(v) => update('climateLeadership', v)} limit={200} /></div>}

      {currentStep === 4 && <div><fieldset><legend className={labelClass}>Select your skills<span className="ml-1 text-[#b17b00]">*</span></legend><div className="mt-3 grid gap-3 sm:grid-cols-2">{fellowshipSkills.map((skill) => <label key={skill} className="flex cursor-pointer items-center gap-3 rounded-xl border border-[#d3e2cf] p-3 text-sm font-semibold text-[#31543b]"><input type="checkbox" checked={values.skills.includes(skill)} onChange={() => toggle('skills', skill)} className="h-5 w-5 accent-[#2f7b45]" />{skill}</label>)}</div></fieldset><div className="mt-7 grid gap-5 sm:grid-cols-2"><SelectField label="How would you rate your digital literacy?" required value={values.digitalLiteracy} onChange={(v) => update('digitalLiteracy', v)} options={['Beginner', 'Intermediate', 'Advanced']} /><SelectField label="How did you hear about the fellowship?" required value={values.referralSource} onChange={(v) => update('referralSource', v)} options={['Facebook', 'Instagram', 'LinkedIn', 'WhatsApp', 'Website', 'School/University', 'Friend/Colleague', 'Community Organization', 'Shara Climate Academy', 'Other']} /><div className="sm:col-span-2"><SelectField label="Are you available throughout the fellowship?" required value={values.availability} onChange={(v) => update('availability', v as 'Yes' | 'No')} options={['Yes', 'No']} /></div></div></div>}

      {currentStep === 5 && <div className="space-y-5"><div className="rounded-2xl bg-[#f7faf4] p-5"><div className="flex gap-3"><LockKeyhole className="mt-1 shrink-0 text-[#2f7b45]" size={20} /><div><h2 className="font-extrabold text-[#164d2b]">Applicant declaration</h2><p className="mt-2 text-sm leading-6 text-[#5b7261]">I confirm that the information provided in this application is accurate and complete to the best of my knowledge. I understand that submission does not guarantee selection into the fellowship.</p></div></div></div><label className="flex items-start gap-3 rounded-xl border border-[#d3e2cf] p-4 text-sm font-bold text-[#31543b]"><input type="checkbox" checked={values.declarationAccepted} onChange={(e) => update('declarationAccepted', e.target.checked as true)} className="mt-0.5 h-5 w-5 accent-[#2f7b45]" />I agree to the applicant declaration.</label><label className="flex items-start gap-3 rounded-xl border border-[#d3e2cf] p-4 text-sm font-bold text-[#31543b]"><input type="checkbox" checked={values.communicationsOptIn} onChange={(e) => update('communicationsOptIn', e.target.checked)} className="mt-0.5 h-5 w-5 accent-[#2f7b45]" />I agree to receive official communication about the fellowship and related Shara Climate Academy activities.</label></div>}

      <div className="mt-9 flex flex-col-reverse justify-between gap-3 border-t border-[#e7efe4] pt-6 sm:flex-row">{currentStep > 0 ? <button type="button" onClick={() => { setError(''); setCurrentStep((step) => step - 1) }} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-[#c8d9c3] px-5 font-bold text-[#31543b] hover:bg-[#f7faf4]"><ArrowLeft size={17} /> Back</button> : <div />}{currentStep < 5 ? <button type="button" onClick={next} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#164d2b] px-7 font-extrabold text-white hover:bg-[#0e3b20]">Continue <ArrowRight size={17} /></button> : <button type="button" disabled={isSubmitting} onClick={() => { if (validateStep()) setShowConfirmation(true) }} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#164d2b] px-7 font-extrabold text-white hover:bg-[#0e3b20] disabled:opacity-60">{isSubmitting && <Loader2 size={17} className="animate-spin" />} Submit application</button>}</div>
    </section>
    {showConfirmation && <div className="fixed inset-0 z-50 grid place-items-center bg-[#102f1c]/70 p-5"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c18f1d]">Final check</p><h2 className="mt-2 text-2xl font-black text-[#164d2b]">Are you sure you want to submit?</h2><p className="mt-3 text-sm leading-6 text-[#65796a]">You will not be able to edit your responses after submission.</p><div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => setShowConfirmation(false)} className="min-h-11 rounded-xl border border-[#c8d9c3] px-5 font-bold text-[#31543b]">Cancel</button><button type="button" onClick={submit} className="min-h-11 rounded-xl bg-[#164d2b] px-5 font-bold text-white">Submit application</button></div></div></div>}
  </div>
}