'use client'

import { useState } from 'react'

type Settings = { title: string; description: string; duration: string; format: string; contactEmail: string; applicationOpen: boolean; maxApplications: number | null }
export function FellowshipSettingsForm({ initialSettings }: { initialSettings: Settings }) {
  const [settings, setSettings] = useState(initialSettings); const [message, setMessage] = useState('')
  const update = (key: keyof Settings, value: string | boolean | number | null) => setSettings((current) => ({ ...current, [key]: value }))
  const save = async (event: React.FormEvent) => { event.preventDefault(); setMessage('Saving...'); const response = await fetch('/api/admin/fellowship', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(settings) }); const result = await response.json(); setMessage(response.ok ? 'Settings saved.' : result.error || 'Unable to save settings.') }
  return <form onSubmit={save} className="max-w-3xl rounded-2xl border border-border bg-card p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold">Fellowship title<input className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" value={settings.title} onChange={(e) => update('title', e.target.value)} /></label><label className="text-sm font-bold">Duration<input className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" value={settings.duration} onChange={(e) => update('duration', e.target.value)} /></label><label className="text-sm font-bold">Contact email<input type="email" className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" value={settings.contactEmail} onChange={(e) => update('contactEmail', e.target.value)} /></label><label className="text-sm font-bold">Maximum applications <span className="font-normal text-muted-foreground">(optional)</span><input type="number" min="1" className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3" value={settings.maxApplications ?? ''} onChange={(e) => update('maxApplications', e.target.value ? Number(e.target.value) : null)} /></label></div><label className="mt-5 block text-sm font-bold">Programme format<textarea className="mt-2 min-h-24 w-full rounded-lg border border-border bg-background p-3" value={settings.format} onChange={(e) => update('format', e.target.value)} /></label><label className="mt-5 block text-sm font-bold">Fellowship description<textarea className="mt-2 min-h-28 w-full rounded-lg border border-border bg-background p-3" value={settings.description} onChange={(e) => update('description', e.target.value)} /></label><label className="mt-5 flex items-center gap-3 text-sm font-bold"><input type="checkbox" className="h-5 w-5 accent-primary" checked={settings.applicationOpen} onChange={(e) => update('applicationOpen', e.target.checked)} /> Applications are open</label><div className="mt-6 flex items-center justify-between gap-4"><p className="text-sm font-semibold text-muted-foreground">{message}</p><button className="rounded-lg bg-primary px-5 py-3 text-sm font-bold text-primary-foreground">Save settings</button></div></form>
}