'use client'

import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Search, ShieldCheck } from 'lucide-react'
import Header from '@/components/header'
import Footer from '@/components/footer'

export default function FellowshipStatusPage() {
  const [applicationId, setApplicationId] = useState(''); const [email, setEmail] = useState(''); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const lookup = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); setResult(null); const response = await fetch(`/api/fellowship/apply?applicationId=${encodeURIComponent(applicationId)}&email=${encodeURIComponent(email)}`); const data = await response.json(); if (!response.ok) setError(data.error); else setResult(data.application); setLoading(false) }
  return <main className="min-h-screen bg-background text-foreground"><Header /><div className="px-4 py-10 sm:px-6 md:px-10 md:py-16"><div className="mx-auto max-w-xl"><Link href="/fellowship" className="inline-flex items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft size={16} /> Back to fellowship</Link><div className="mt-10 rounded-2xl border border-border bg-card p-7 shadow-sm sm:p-10"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-secondary text-primary"><Search size={22} /></div><p className="mt-7 text-xs font-bold uppercase tracking-[.2em] text-accent-foreground">Applicant portal</p><h1 className="mt-2 text-4xl font-black text-primary">Check application status</h1><p className="mt-4 leading-7 text-muted-foreground">Enter your application ID. Adding your email gives us an extra way to verify your record.</p><form onSubmit={lookup} className="mt-8 space-y-5"><label className="block text-sm font-bold text-foreground">Application ID<input required className="mt-2 min-h-12 w-full rounded-lg border border-border bg-background px-4 uppercase outline-none focus:border-primary" value={applicationId} onChange={(e) => setApplicationId(e.target.value)} placeholder="SCCF-2026-00001" /></label><label className="block text-sm font-bold text-foreground">Email address <span className="font-normal text-muted-foreground">(optional)</span><input type="email" className="mt-2 min-h-12 w-full rounded-lg border border-border bg-background px-4 outline-none focus:border-primary" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label>{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}<button disabled={loading} className="min-h-12 w-full rounded-lg bg-primary font-extrabold text-primary-foreground disabled:opacity-60">{loading ? 'Checking...' : 'Check status'}</button></form>{result && <div className="mt-8 rounded-lg border border-primary/30 bg-secondary p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-primary" size={22} /><p className="font-extrabold text-primary">Application found</p></div><p className="mt-5 text-sm text-muted-foreground">{result.applicantName}</p><p className="mt-1 font-mono text-sm font-bold text-primary">{result.applicationId}</p><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-muted-foreground">Current status</p><p className="mt-1 text-2xl font-black text-primary">{result.status}</p></div>}</div></div></div><Footer /></main>
}